ALTER TABLE public.purchasing
ADD COLUMN IF NOT EXISTS unit_model TEXT,
ADD COLUMN IF NOT EXISTS plate_number TEXT,
ADD COLUMN IF NOT EXISTS vehicle_owner TEXT,
ADD COLUMN IF NOT EXISTS customer_type TEXT,
ADD COLUMN IF NOT EXISTS insurance_company_name TEXT,
ADD COLUMN IF NOT EXISTS pr_number TEXT,
ADD COLUMN IF NOT EXISTS is_po_synced BOOLEAN DEFAULT FALSE;
