"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Loader2, Brain, FileText, Sparkles } from "lucide-react"

export default function AITestPage() {
    const [loading, setLoading] = useState(false)
    const [report, setReport] = useState<string | null>(null)
    const [error, setError] = useState<string | null>(null)

    const generateTestReport = async () => {
        setLoading(true)
        setError(null)
        setReport(null)

        try {
            // For testing, we'll try to get reports for February 2026 (current month)
            const response = await fetch("/api/admin/ai-report", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    month: 2,
                    year: 2026
                })
            })

            const data = await response.json()

            if (!response.ok) {
                throw new Error(data.error || "Failed to generate report")
            }

            setReport(data.report)
        } catch (err) {
            setError(err instanceof Error ? err.message : "Something went wrong")
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className="p-8 max-w-4xl mx-auto space-y-8">
            <div className="flex flex-col items-center text-center space-y-4">
                <div className="p-3 bg-primary/10 rounded-full text-primary">
                    <Brain className="w-12 h-12" />
                </div>
                <h1 className="text-4xl font-bold tracking-tight">AI Business Analyst Test</h1>
                <p className="text-muted-foreground text-lg max-w-2xl">
                    Test the new AI Intelligence System for Autoworx. This will analyze your history data for February 2026.
                </p>
                <Button
                    onClick={generateTestReport}
                    disabled={loading}
                    size="lg"
                    className="gap-2 text-lg px-8 py-6 rounded-full shadow-lg hover:shadow-primary/20 transition-all font-bold"
                >
                    {loading ? (
                        <>
                            <Loader2 className="w-5 h-5 animate-spin" />
                            AI is analyzing your data...
                        </>
                    ) : (
                        <>
                            <Sparkles className="w-5 h-5" />
                            Generate AI Monthly Report
                        </>
                    )}
                </Button>
            </div>

            {error && (
                <div className="p-4 bg-destructive/10 border border-destructive/20 text-destructive rounded-lg text-center font-medium animate-in fade-in slide-in-from-top-2 duration-300">
                    {error}
                    {error.includes("No data found") && (
                        <p className="text-sm mt-1 opacity-80">Make sure you have archived some appointments in February 2026 first!</p>
                    )}
                </div>
            )}

            {report && (
                <Card className="border-primary/20 shadow-2xl animate-in zoom-in-95 fade-in duration-500 overflow-hidden">
                    <CardHeader className="bg-primary/5 border-b border-primary/10 py-6">
                        <CardTitle className="flex items-center gap-3 text-2xl">
                            <FileText className="w-7 h-7 text-primary" />
                            Monthly Business Briefing
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="p-8">
                        <div className="prose prose-slate dark:prose-invert max-w-none prose-headings:text-primary prose-a:text-primary prose-strong:text-foreground">
                            {/* Note: In a real app we'd use a markdown parser, but for this test we'll just show text */}
                            <pre className="whitespace-pre-wrap font-sans text-lg leading-relaxed text-foreground/90">
                                {report}
                            </pre>
                        </div>
                        <div className="mt-8 pt-6 border-t border-border flex justify-between items-center text-sm text-muted-foreground italic">
                            <p>Generated by Autoworx AIS (Automotive Intelligence System)</p>
                            <p>February 2026</p>
                        </div>
                    </CardContent>
                </Card>
            )}
        </div>
    )
}
